### ISSUE TITLE
AssemblyScript compilation

### ISSUE THREAD

**Issue by queequac** [dead/typeflex#2]
> And it is possible to compile it to WebAssembly using AssemblyScript.

Did you actually try this? If yes, do you have some instruction how to compile to WASM? Any attempt from my side ended up in errors from the AssemblyScript compiler. :(

**Comment by queequac** [comment]
I guess the hint on the project page is just hypothetical. I have seen type unions, `any`, and similar constructs in the code, which are not supported by AssemblyScript. Too bad. :(

**Comment by dead** [comment]
Yeah, it's just hypothetical. But I almost did some time ago. I'll try again this weekend. 😄
