### ISSUE TITLE
ALIGN_STRETCH option for setAlignItems does not work.

### ISSUE THREAD

**Issue by barefists** [dead/typeflex#5]
Setting Node.setAlignItems to ALIGN_STRETCH has the same effect as setting it to ALIGN_FLEX_START.

**Comment by dead** [comment]
Hi @barefists! Can you provide an example?
I was playing around the yoga playground and it seems that the stretch only works if I remove the height (or width if the flex direction is column) from the items or use min-height instead. (https://tinyurl.com/y2tsjktp)

**Comment by barefists** [comment]
Ah I see! It's working now thanks!
